### ISSUE TITLE
Make Pricing Table on Booking Page Mobile Responsive

### ISSUE THREAD

**Issue by strawhat19** [Piratechs-LLC/Project-Escape#1]

**Comment by Xuruko** [comment]
Code won't actually update when I try and preview changes? I believe I'm close to solving this issue but when I try and preview changes to the actual CSS of the page, it doesn't update to new numbers.

**Comment by Xuruko** [comment]
Stuck on the tiny aesthetic lines next to "All Rooms Are Private."
