### ISSUE TITLE
Disable Contact Forms and Replace with Basic Contact Details Section

### ISSUE THREAD

**Issue by strawhat19** [Piratechs-LLC/Project-Escape#10]
- [x] Disable current contact form on home page and contact page and corporate events page (if its live)
- [x] Replace with just a normal section, with stylized text or graphics, that contains their basic contact info
- [x] Example: ![Image](https://user-images.githubusercontent.com/85896950/183301970-b5bf15c1-ee80-48e5-93be-82004e5597e1.png)

**Comment by kaymiika** [comment]
> * [ ]  Disable current contact form on home page and contact page and corporate events page (if its live)
> * [ ]  Replace with just a normal section, with stylized text or graphics, that contains their basic contact info
> * [ ]  Example: ![Image](https://user-images.githubusercontent.com/85896950/183301970-b5bf15c1-ee80-48e5-93be-82004e5597e1.png)

**Comment by Xuruko** [comment]
> * [ ]  Disable current contact form on home page and contact page and corporate events page (if its live)
> * [ ]  Replace with just a normal section, with stylized text or graphics, that contains their basic contact info
> * [ ]  Example: ![Image](https://user-images.githubusercontent.com/85896950/183301970-b5bf15c1-ee80-48e5-93be-82004e5597e1.png)

> Chandler
>Unpaid = 2. Disabled contact form on Home Page and Team Building Page. Placed new section on Home Page. Still in process on the Team Building Page. Planning to create something different instead of re-using the same one from the Contact Page.
