### ISSUE TITLE
Add New Slide to Project Escape Slider which more Prominently Discusses the Party Room

### ISSUE THREAD

**Issue by strawhat19** [Piratechs-LLC/Project-Escape#11]
- [x] Make new Party Room Page
     - [x] Ensure it is mobile responsive 
- [x] Add New Slide to Homepage Slideshow for Party Room
- [x] Change Link on Experiences Page to Redirect to New Party Room Page
- [x] Change "Scavenger Hunt" Tile on Homepage to "Party Room" Tile
     - [x] ![Image](https://user-images.githubusercontent.com/85896950/185269708-44a67f5e-4418-4602-9af7-949c62a863a3.png)

**Comment by Xuruko** [comment]
Chandler
- Unpaid = 3

- Edited slides and created new Party Room Page. In need of more pictures honestly.
