### ISSUE TITLE
Design & Add Guaranteed Time Slot to WordPress Site

### ISSUE THREAD

**Issue by strawhat19** [Piratechs-LLC/Project-Escape#3]
- [x] Brandy said
      ![image](https://user-images.githubusercontent.com/85896950/179157531-6494b5eb-10c4-4917-938a-ce9668abd14b.png)
 - [x] She was referring to this thing she saw on some other site
      ![image](https://user-images.githubusercontent.com/85896950/179157512-0558a871-8658-4dda-885a-931d193ca422.png)
 - [x] So we need to add something we custom designed with similar wording to this page
     ![Image](https://user-images.githubusercontent.com/85896950/179463029-f59b1099-e39f-4842-ac0d-020b98458a4f.jpg)

**Comment by Xuruko** [comment]
Need to change Icon to something actually relevant. Have one in mind but can't locate in the Fontawesome bin
